# -*- coding: utf-8 -*-
"""Copy of Practice_Assignmen_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kE5XQhb321dBEU0NFBHsL8eUIUDDhtLI

# Topic: print()

1) Using the python print function print any string value, integer value, boolean value, float value in single print command
"""

print("Bismillah",313,True,26.11)

"""2) Using the python print function print hyphon(-) separated any string value, integer value, boolean value, float value in single print command"""

print("hello" ,98 ,True ,98.5 ,sep='-')

"""3) Using the python print function print any string value, integer value, boolean value, float value in separate print command.
But every value must be space separated and in single line
"""

print("hello", end = ' ')
print(98 , end = ' ')
print(True , end = ' ')
print(98.5 , end = ' ')

"""4) Can a python print function take no value to print???

"""

print("")

"""# TOPIC :Variables in Python Operators

5) One of my friends name is Mr. Ahmed. He is 30 years old.  He is a lawer by profession. He has done his bachelors in law in the year 2005. He is working with a reputable law firm 'The Himalya Associates' in Karachi since 2015.
He is a handsome lawer with height of 5.10 feets and weight 70600g. His monthly income is Rs. 200k PKR.

Note: Create variables from above text and also assign values from the text.
"""

name = "Mr. Ahmed"
age = 30
profession = lawyer
education = "bachelors in law"
graduation_year = 2005
weight = 70600g
height = 5.10
monthly_income = 200000

"""6)How many years has been to Mr. Ahmed after his bachelors degree? Create a variable that hold current year value and then subtract it from his passout year"""

current_year = 2024
graduation_year = 2005
current_year - graduation_year

"""7) How many years has Mr. Ahmed been working with law firm 'The Himalya Associates'. Create necesary variables and print the correct number of years in working in the firm"""

joining_year = 2015
current_year = 2024
current_year - joining_year

"""8)Convert the monthly income of Mr. Ahmed in dollars.  Create necesary variables and print the income in dollars."""

dollar = 277.80
monthly_income = 200000
monthly_income_in_dollars = monthly_income//dollar
print(monthly_income_in_dollars)

"""9) Check if the income in dollars is a float or integer value. if it is float, re-write the code so that income gets converted in integer. print the income in integer type value"""

dollar = int(277.80)
monthly_income = 200000
monthly_income_in_dollars = monthly_income//dollar
print(type(monthly_income_in_dollars))
print(monthly_income_in_dollars)

"""10) Print the type of Mr. Ahmed's weight. Convert the weight of Mr. Ahmed in kg so that weight must be a integer value.

"""

weight_in_grams = 70600
weight_in_kilograms = weight_in_grams // 1000
print(weight_in_kilograms)

"""#11) print the year of birth of Mr. Ahmed."""

current_year = 2024
age = 30
year_of_birth = current_year - age
print(year_of_birth)

"""12) Can Rs. 100 be divided equally among 6 students?
HINT: % operator (modulo)
"""

print(f'each person get: {100//6}')

print(f"Left after division: {100%6}")

"""                       Saylani Mass IT
             Name   : Nasir Hussain
             Course : AI and DS
             Days   : Tuesday and Thursday
             ID     : AI - 332909


"""

Institute = "Saylani Mass IT"
Name = "Nasir Hussain"
Course = "AI and DS"
Days = "Tuesday and Thursday"
ID = "AI - 332909"

print(f"Institute {Institute}\n Name {Name}\n Course {Course}\n Days {Days}\n ID {ID}")