# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNcbf29eH9vZfQkQJ5urUlNT8LmNURFU

#Questions:
## 1) Area of a Rectangle:
Write a Python program to calculate the area of a rectangle. Use the formula:
𝐴𝒓𝒆𝒂 = 𝒍𝒆𝒏𝒈𝒕𝒉 × 𝒘𝒊𝒅𝒕𝒉
Take length and width as inputs from the user.
"""

# Consider a rectangle having sides a & b
side_a = 4
side_b = 5
area = side_a * side_b
print(area)

"""## 2) Circumference of a Circle:
Write a Python program to calculate the circumference of a circle. Use the formula:
𝑪𝒊𝒓𝒄𝒖𝒎𝒇𝒆𝒓𝒆𝒏𝒄𝒆 = 𝟐𝝅𝒓
Take the radius r as input from the user.
"""

# Consider a circle of diameter D and radius r
d = 8
r = d/2
circumference = 2*3.14*r
print(circumference)

"""## 3) Simple Interest:
Write a Python program to calculate the simple interest. Use the formula:
𝑺𝒊𝒎𝒑𝒍𝒆 𝑰𝒏𝒕𝒆𝒓𝒆𝒔𝒕 = 𝑷𝒓𝒊𝒏𝒄𝒊𝒑𝒂𝒍 × 𝑹𝒂𝒕𝒆 × 𝑻𝒊𝒎𝒆
Take Principal, Rate, and Time as inputs from the user.
"""

principal = float(input("Enter the principal amount: "))
rate = float(input("Enter the rate of interest: "))
time = float(input("Enter the time in years: "))
simple_interest = principal*rate*time
print(simple_interest)

"""##4) Speed of an Object:
Write a Python program to calculate the speed of an object. Use the formula:
𝑆𝒑𝒆𝒆𝒅 = 𝑫𝒊𝒔𝒕𝒂𝒏𝒄𝒆 / 𝑻𝒊𝒎𝒆
Take Distance and Time as inputs from the user.

"""

# Consider an object with speed = s , distance = d and time = t.
d = float(input("Enter the distance in meters: "))
t = float(input("Enter the time seconds: "))
speed = d/t
print(speed)

"""##5) BMI Calculator:
Write a Python program to calculate the Body Mass Index (BMI). Use the formula:
BMI = Weight(kg)/Height^2
 Take Weight (in kilograms) and Height (in meters) as inputs from the user.
"""

# For BMI
weight = float(input("Enter the weight in kilograms: "))
height = float(input("Enter the height in meters: "))
BMI = weight/(height**2)
print(BMI)
#

"""##6) Force Using Newton's Second Law:
Write a Python program to calculate the force on an object. Use the formula: F=ma
Take m (mass in kilograms) and a (acceleration in meters/second²) as inputs from the
user.

"""

# Calculating force using newton's 2nd law of motion
m = float(input("Enater the mass in kilorams: "))
a = float(input("Enter the acceleration in m/s^2: "))
f = m*a
print(f"{f} Newton")

"""## 7) Compound Interest:
Write a Python program to calculate compound interest. Use the formula:
A = P (1 + r/n)^n-t
Where:
A= total amount
P = principal amount
r = annual interest rate (decimal)
n = number of times interest is compounded per year
t = time in years
Take P, r, n, and t as inputs from the user.
"""

# For Compound interest
P = float(input("Enter the principal amount in PKR: "))
r = float(input("Enter the annual interest rate in decimal:"))
n = float(input("Enter the number of times interest is compounded per year: "))
t = float(input("Enter the time in years: "))
A = P*(1+r/n)**(n-t)
print(A)

"""## 8) Perimeter of a Triangle:
Write a Python program to calculate the perimeter of a triangle. Use the formula:
𝑷𝒆𝒓𝒊𝒎𝒆𝒕𝒆𝒓 = 𝒂 + 𝒃 + 𝒄
Take a, b, and c (lengths of the three sides) as inputs from the user.
"""

# For perimeter of a triangle
a = float(input("Enter the length of side a in meter: "))
b = float(input("Enter the length of side b in meter: "))
c = float(input("Enter the length of side c in meter: "))
Perimeter = a+b+c
print(Perimeter)

"""## 9) Volume of a Sphere:
Write a Python program to calculate the volume of a sphere. Use the formula:
Volume = 4/3 * (3.14) * r ** 3
Take r (radius) as input from the user.
"""

# For volume of sphere
r = float(input("Enter the radius of sphere in meter: "))
Volume = (4/3)*(3.14)*(r**3)
print(Volume)

"""## 10) Kinetic Energy:
Write a Python program to calculate the kinetic energy of an object. Use the formula:
𝑲𝑬 = 1/2 (m/v*2)
Take m (mass in kilograms) and v (velocity in meters/second) as inputs from the user.

"""

# For Kinetic Energy
m = float(input("Enter the mass in kilograms: "))
v = float(input("Enter the velocity in meters/second: "))
KE = 1/2*(m/v**2)
print(KE)

"""## 11) Quadratic Equation Roots:
Write a Python program to find the roots of a quadratic equation. Use the formula:
X = (-b ± √(b²-4ac)) / (2a)
Take a, b, and c as inputs from the user.
"""

# For Quadratic formula
import cmath

b = float(input("Enter the value of b: "))
c = float(input("Enter the value of c: "))
a = float(input("Enter the value of a: "))

# Use cmath.sqrt for complex numbers
X1 = (-b + cmath.sqrt(b**2 - 4*a*c)) / (2*a)
X2 = (-b - cmath.sqrt(b**2 - 4*a*c)) / (2*a)
X  = X1 + X2
print(X)

"""## 12) Temperature Conversion:
Write a Python program to convert a temperature from Celsius to Fahrenheit. Use the
formula: F = (9/5) C + 32
Take C (temperature in Celsius) as input from the user.
"""

# For Temperature in Farenheit
C = float(input("Enter the temperature in Celsius: "))
F = (9/5)*C + 32
print(F)

"""## 13) Gravitational Force:
Write a Python program to calculate the gravitational force between two objects. Use
the formula
F=G m1m2/r^2
m1, m2 are the masses of the objects
r = distance between the centers of the objects
Take m1, m2 and r as inputs from the user.

"""

# For Gravitational force
G = 6.67430e-11
m1 = float(input("Enter the mass of object 1 in kilograms: "))
m2 = float(input("Enter the mass of object 2 in kilograms: "))
r = float(input("Enter the distance between the centres of objects in meters: "))
F = G*m1*m2/(r**2)
print(F)

"""##14) Volume of a Cylinder:
Write a Python program to calculate the volume of a cylinder. Use the formula:
𝑽𝒐𝒍𝒖𝒎𝒆 = 𝝅𝒓^𝟐𝒉
Take radius(r) and height(h) as inputs from the user
"""

# For volume of cylinder

r = float(input("Enter the radius of cylinder in meters: "))
h = float(input("Enter the height of cylinder in meters: "))
V = 3.14*(r**2)*h
print(V)

"""##15) Pressure:
Write a Python program to calculate the pressure exerted by a force on a surface. Use
the formula:
𝑷 = F/A
P = pressure
F = force
A = area
Take F(force) and A(area) as inputs from the user.

"""

# For Pressure

F = float(input("Enter the force in Newtons: "))
A = float(input("Enter the area in square meters: "))
P = F/A
print(P)

"""##16) Electric Power:
Write a Python program to calculate the electric power consumed. Use the formula: P = V/I
where:
P = power
V = voltage
I = current
Take V(voltage) and I(current) as inputs from the user.

"""

# For Electric Power

V = float(input("Enter the voltage in volts: "))
I = float(input("Enter the current in Ampers: "))
P = V/I
print(P)

"""##17) Perimeter of a Circle (Circumference):
Write a Python program to calculate the perimeter (circumference) of a circle. Use the
formula: P= 2(3.14)r
Take r (radius) as input from the user.
"""

# For Circumference of a circle

r = float(input("Enter the radius of circle in meters: "))
P = 2*3.14*r
print(P)

"""##18) Future Value in Savings:
Write a Python program to calculate the future value of an investment. Use the formula:
𝐹𝑉 = 𝑃𝑉(1 + 𝑟)^t
where:
o FV= future value
o PV= present value
o r= annual interest rate (as a decimal)
o t= time in years
Take PV, r, and t as inputs from the user.

"""

# For future value

PV = float(input("Enter the present value in PKR: "))
r = float(input("Enter the annual interest rate in decimal: "))
t = float(input("Enter the time in years: "))
FV = PV*(1+r)**t
print(FV)

"""##19) Work Done by a Force:
Write a Python program to calculate the work done by a force. Use the formula: W=f.d cos
where:
W = work done
f= force
d = distance
theta = angle between force and direction of movement (in degrees)
Take f, d, and θ as inputs from the user.

"""

# For work done
import math

f = float(input("Enter the value of force: "))
d = float(input("Enter the value of distance: "))
theta = float(input("Enter the angle between force and direction of movement in degrees: "))
W = f*d* math.cos(theta)
print(W)

"""##20) Heat Transfer:
Write a Python program to calculate the amount of heat transferred. Use the formula:
𝑄 = 𝑚𝑐 (∆T)
where:
Q= heat transfer
m = mass
c = specific heat capacity
ΔT
Take m, c, T as inputs from the user

"""

# For Heat Transfer

m = float(input("Enter the mass of object: "))
c = float(input("Enter the specific heat capacity of object: "))
T = float(input("Enter the temperature difference: "))
Q = m*c*T
print(Q)